version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: farmaalg-sandbox
    expose:
      - '4444'
    ports:
      - '4444:4444'
    command: npm run dev
    volumes:
      - ./src:/app/sandbox/src
      - ./scripts:/app/sandbox/scripts
      - ./nodemon.json:/app/sandbox/nodemon.json
